name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build all
      run: yarn prepare

    - name: Unit test
      run: yarn test

    - name: Build docs
      run: yarn run build-docs
